(cl:in-package custom_msg-msg)
(cl:export '(SET_OMB-VAL
          SET_OMB
          SET_COT-VAL
          SET_COT
          SET_PUN-VAL
          SET_PUN
          SET_GAR-VAL
          SET_GAR
          RESET-VAL
          RESET
          RETRY-VAL
          RETRY
          EMERGENCY_STOP-VAL
          EMERGENCY_STOP
          SET_KP_PUN-VAL
          SET_KP_PUN
          SET_KI_PUN-VAL
          SET_KI_PUN
          SET_KD_PUN-VAL
          SET_KD_PUN
          SET_KP_OMB-VAL
          SET_KP_OMB
          SET_KI_OMB-VAL
          SET_KI_OMB
          SET_KD_OMB-VAL
          SET_KD_OMB
          SET_KP_GAR-VAL
          SET_KP_GAR
          SET_KI_GAR-VAL
          SET_KI_GAR
          SET_KD_GAR-VAL
          SET_KD_GAR
))