// Generated by gencpp from file custom_msg/reset_COT.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_RESET_COT_H
#define CUSTOM_MSG_MESSAGE_RESET_COT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg
{
template <class ContainerAllocator>
struct reset_COT_
{
  typedef reset_COT_<ContainerAllocator> Type;

  reset_COT_()
    : reset_COT(false)  {
    }
  reset_COT_(const ContainerAllocator& _alloc)
    : reset_COT(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_COT_type;
  _reset_COT_type reset_COT;





  typedef boost::shared_ptr< ::custom_msg::reset_COT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::reset_COT_<ContainerAllocator> const> ConstPtr;

}; // struct reset_COT_

typedef ::custom_msg::reset_COT_<std::allocator<void> > reset_COT;

typedef boost::shared_ptr< ::custom_msg::reset_COT > reset_COTPtr;
typedef boost::shared_ptr< ::custom_msg::reset_COT const> reset_COTConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::reset_COT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::reset_COT_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg::reset_COT_<ContainerAllocator1> & lhs, const ::custom_msg::reset_COT_<ContainerAllocator2> & rhs)
{
  return lhs.reset_COT == rhs.reset_COT;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg::reset_COT_<ContainerAllocator1> & lhs, const ::custom_msg::reset_COT_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::reset_COT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::reset_COT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::reset_COT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::reset_COT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::reset_COT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::reset_COT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::reset_COT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8be9f92adaf46f35e0791e11db65f1f5";
  }

  static const char* value(const ::custom_msg::reset_COT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8be9f92adaf46f35ULL;
  static const uint64_t static_value2 = 0xe0791e11db65f1f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::reset_COT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/reset_COT";
  }

  static const char* value(const ::custom_msg::reset_COT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::reset_COT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset_COT\n"
;
  }

  static const char* value(const ::custom_msg::reset_COT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::reset_COT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset_COT);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_COT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::reset_COT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::reset_COT_<ContainerAllocator>& v)
  {
    s << indent << "reset_COT: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset_COT);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_RESET_COT_H
